import java.util.ArrayList;

public class getSegments {
    private String kmer;
    //String kmer = "TCCACTAGAACGATACGGTATCCACGTAAGCGATCTCTTAGGTATGCCGACAAGGTCAAGAACATTACACGCCACAACATGTGGAATGGAGATGCCTATTCACCTATACGAGGCCCTCATCTCACCGTTGCCTTCATGCCGGAGCGTGACACAAGGTGTGTTGGTTTGGGTGACTGTCACCTTCCGAATCGCGACCAGAGGGAACTATCACAGCAGGCTGACCCGCCTACCTAAACGCAACCTCCGTCTAACACACCTATCACACGATGGTAGTGTTGGCTCGATAGGACCACTAAAAACTAAAGCGGATTCCGCCGCTGGGGTGTTGCAATGGCTTAAGGCTCCACTCAGGTCCACTTCCGAGACCGTTTCTCCCGATCACGTAGCCTACAAATAGGAGTGTTATTATGGCTGGCCATATCATAACGAAGGACTGAGGGGCGGGAAAAGCAATCATCTGAAGATATAAGGAAAGTAGGGCCGAGCGCTATCTACTACGGTGATCTCCTATGATTATCGCTGAAAATTCGCGGCCTGAGAGCGCTGGCTTAGCAGGAGGGCAGTCATAACTAATGACCACCTCAAACGCACTCCAGTGTTCCATTGAGGAGGCATGCAAGGCCATAGGCATGTCTCGAGTTTTATACCGACAGAAGACATTGCTTACCAATTCTTCGCCGGTAATCCCAGGTTATAGCAGCCTCCGAACATGGCGTCCCGTCAGACTTTAACTCCCGGGTACCTTCAATATGAGCCTGATTTCCCCAGCTCGGTGACCGGTGGGGCCTGCGGTAAGCATTTTCCCCGTAAATGCGTGATACTCGTATAGGGCTAGCGCGCCGGAATGGTACCCTTAGGGTGCAAGACCATTAGCCAGTAATGTCGGCCCGGACATGTCGAACAGCCAAATACTTGCGCTATTACATCCAAACTGCACTGACGGCCATCTTGACGTCTCACCTGTCCCGACCCTACAGTACATACTTTTCGTGGATATTCT";
    public ArrayList<String> getSegments(String str){
         kmer = str;
         String ans = "";
        int len = 10;
        ArrayList<String> strs = new ArrayList<>();
        for(int i = 0; i <= kmer.length(); i++){
        if(i + len <= kmer.length()) {
            strs.add(kmer.substring(i, i + len));
        }
        }
        return strs;
    }

}